-- Domain renewals (2026-10-10): one row per reminder or automatic renewal invoice sent for a given expiry date, so the
-- daily job never sends the same notice twice and never issues two automatic invoices for one renewal period.
CREATE TABLE domains_renewalnotice (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id uuid NOT NULL REFERENCES domains_domain(id) ON DELETE CASCADE,
    kind character varying(20) NOT NULL,
    expires_at date NOT NULL,
    order_id uuid NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT domains_renewalnotice_unique UNIQUE (domain_id, kind, expires_at)
);
CREATE INDEX domains_renewalnotice_domain_idx ON domains_renewalnotice (domain_id);
