import { Link } from '@/lib/navigation'
import { ArrowRight, Code2, LifeBuoy } from 'lucide-react'
import { CustomerHeader } from '../components/CustomerHeader'
import { SiteFooter } from '../components/SiteFooter'
import { PageIntro } from '../components/PageIntro'
import { Notice } from '../components/Notice'
import { SEO } from '../components/SEO'
import { INARA_CREST } from '../lib/site'
export function DevelopersPage() {
  return <div className="public-page bg-maven-paper"><CustomerHeader /><SEO title="Developers & Inara Devs | MavenHost" description="Host your own project with MavenHost or request developers through Inara Devs for application development and maintenance." path="/developers" /><PageIntro eyebrow="Developers" title="Need a developer? Meet Inara Devs." description="Inara Devs connects you with developers for websites, applications and ongoing software maintenance. Discuss your project and agree on the scope separately from your MavenHost domain and hosting plan."><a href={INARA_CREST.developers} target="_blank" rel="noreferrer" className="btn btn-primary">Request a developer <span className="sr-only">(opens in a new tab)</span><ArrowRight className="size-4" /></a><Link to="/hosting" className="btn btn-secondary">Compare hosting</Link></PageIntro>
  <main id="main-content" className="container-shell section-space"><Notice title="Confirm the environment first.">Hosting configurations are pending supplier activation. Check the exact runtime, database and deployment requirements with support before assuming a package can run your application.</Notice>
    <section id="runtime-checklist" className="section-space grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="eyebrow">Deployment checklist</p><h2 className="mt-3 text-2xl font-semibold text-maven-text">Match the hosting environment to your software.</h2><p className="mt-3 text-sm leading-7 text-maven-muted">A website allowance or storage figure does not establish compatibility with a particular framework. Review the complete configuration, not just its headline price.</p></div><ol className="steps-list"><li><h3>Language and database versions</h3><p>Specify PHP, Python or Node requirements and the database engine and version. Do not assume PostgreSQL support, unrestricted Node services or a particular Django environment from shared hosting alone.</p></li><li><h3>Deployment access and processes</h3><p>Confirm SSH, Git, file transfer, scheduled jobs, environment variables and whether your application needs persistent workers or background services. Access depends on the selected product.</p></li><li><h3>Resources and control panels</h3><p>Cloud hosting plans host the listed websites in one hosting account with SSH, Git and WP-CLI access. Server panels, licences and management scope need configuration-specific confirmation.</p></li><li><h3>Your operating responsibilities</h3><p>Keep code and dependencies updated, test releases, maintain independent backups and monitor application behaviour. Supplier infrastructure management does not include repairing your custom code.</p></li></ol></section>
    <section id="engineering-help" className="section-space border-t border-maven-line"><p className="eyebrow">Two distinct kinds of help</p><div className="mt-6 grid gap-8 md:grid-cols-2"><article className="service-summary"><LifeBuoy className="size-5 text-maven-signal" /><h2>MavenHost platform support</h2><p>Ask about purchased domains, account access, DNS controls, plan specifications, billing or a hosting service issue. Include your service and order reference; the approved support scope determines what can be handled.</p><Link to="/contact?type=support">Get hosting support <ArrowRight className="size-4" /></Link></article><article className="service-summary"><Code2 className="size-5 text-maven-signal" /><h2>Development through Inara Devs</h2><p>Request developers for a new project, improvements to existing software or ongoing maintenance. Scope and fees are agreed directly through Inara Devs.</p><a href={INARA_CREST.developers} target="_blank" rel="noreferrer">Visit Inara Devs <span className="sr-only">(opens in a new tab)</span><ArrowRight className="size-4" /></a></article></div><Notice title="Separate purchases and agreements.">MavenHost customers pay the prices in their selected packages. Any registration or renewal included under an Inara Crest project depends on that engagement’s agreement. A MavenHost account does not include development services or automatic access to another platform.</Notice></section>
  </main><SiteFooter /></div>
}
