import { Link } from '@/lib/navigation'
import { ArrowRight, ArrowRightLeft, Code2, Globe2, Mail, Server } from 'lucide-react'
import { CustomerHeader } from '../components/CustomerHeader'
import { SiteFooter } from '../components/SiteFooter'
import { DomainSearch } from '../features/domain/DomainSearch'
import { SEO } from '../components/SEO'
import { SectionHeading } from '../components/SectionHeading'
import { PlanPrice } from '../components/PlanPrice'
import { Notice } from '../components/Notice'
import { featureValue, useHostingCatalog } from '../lib/hosting-presentation'
import { INARA_CREST } from '../lib/site'
const JOURNEYS = [
  { icon: Globe2, title: 'Find your domain', body: 'Check a business name and compare available extensions. Registration and hosting are separate purchases.', to: '/domains', action: 'Search a domain' },
  { icon: Server, title: 'Host an existing website', body: 'Compare website, storage and email limits. You can use a domain you already own.', to: '/hosting', action: 'Compare hosting' },
  { icon: ArrowRightLeft, title: 'Move a website or domain', body: 'Confirm transfer eligibility, migration scope and any charges before moving files, DNS or email.', to: '/contact?type=support&subject=Migration%20and%20domain%20transfer', action: 'Discuss a move' },
  { icon: Mail, title: 'Set up business email', body: 'Review the mailboxes included in cPanel hosting. Account storage is shared by websites and email.', to: '/hosting?category=email', action: 'Review email options' },
]
export function HomePage() {
  const { plans, loading, error, retry } = useHostingCatalog()
  const shared = plans.filter(plan => plan.plan_type === 'shared').slice(0, 4)
  return <div className="public-page bg-maven-paper"><CustomerHeader /><SEO title="Domains, Website Hosting & Business Email | MavenHost" description="Search domains, compare cPanel hosting and business email, and get help with transfers. Clear billing periods, plan limits and support for independent developers." path="/" />
    <main id="main-content">
      <section className="hero-neutral home-intro"><div className="container-shell">
        <div className="grid items-start gap-8 lg:grid-cols-[1.4fr_0.6fr]"><div><p className="eyebrow">Domains · hosting · platform support</p><h1>One place for your domain, website and business email.</h1><p className="intro-copy">MavenHost helps businesses and independent developers choose domains and hosting with clear resource limits and billing periods. Bring an existing site or start with a name.</p></div><aside className="border-l-2 border-maven-line pl-6 text-sm leading-6 text-maven-muted"><p className="font-semibold text-maven-text">Know what you are choosing.</p><p className="mt-2">Domain registration, website hosting and development are different services. Choose each one when you need it, without assuming that a hosting plan includes a paid domain or engineering work.</p><Link to="/contact?type=general" className="mt-4 inline-flex items-center gap-2 font-semibold text-maven-signal">Help me choose <ArrowRight className="size-4" /></Link></aside></div>
        <div id="domains" className="panel mt-8 scroll-mt-52 p-2"><DomainSearch compact /></div>
        <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm font-medium text-maven-signal"><Link to="/hosting">Compare hosting</Link><Link to="/domains#domain-transfer-heading">Transfer a domain</Link><Link to="/developers">Hosting for developers</Link></div>
      </div></section>
      <section className="section-space border-y border-maven-line"><div className="container-shell"><SectionHeading kicker="Choose your next step" title="Start with the service your project needs." /><div className="mt-8 grid gap-x-8 gap-y-6 md:grid-cols-2 xl:grid-cols-4">{JOURNEYS.map(({ icon: Icon, ...item }) => <article key={item.title} className="service-summary"><Icon className="size-5 text-maven-signal" /><h3>{item.title}</h3><p>{item.body}</p><Link to={item.to}>{item.action} <ArrowRight className="size-4" /></Link></article>)}</div></div></section>
      <section className="section-space"><div className="container-shell"><div className="flex flex-wrap items-end justify-between gap-4"><SectionHeading kicker="Website hosting" title="Compare the essentials before choosing." description="Published configurations from the hosting catalog. Prices below use the one-year billing period, with the full amount shown first." /><Link to="/hosting#compare-plans" className="btn btn-secondary">Full plan comparison</Link></div><Notice title="Hosting launch status.">You can compare and add plans to your cart. Hosting checkout and account setup are not open yet; no payment is collected for these selections.</Notice>{loading && <p role="status" className="py-8 text-maven-muted">Loading current hosting plans…</p>}{error && <div role="alert" className="py-6"><p>{error}</p><button type="button" onClick={retry} className="btn btn-secondary mt-3">Retry catalog</button></div>}{!loading && !error && shared.length === 0 && <p className="py-6 text-maven-muted">No website hosting plans are currently listed. Contact support for options.</p>}<div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{shared.map(plan => <article key={plan.id} className="panel p-5"><h3 className="text-lg font-semibold text-maven-text">{plan.name}</h3><PlanPrice plan={plan} term="1-year" /><dl className="compact-specs"><div><dt>Websites</dt><dd>{featureValue(plan, 'websites')}</dd></div><div><dt>Storage</dt><dd>{featureValue(plan, 'storage_gb', ' GB')}</dd></div><div><dt>Mailboxes</dt><dd>{featureValue(plan, 'max_email_accounts')}</dd></div></dl><Link to="/hosting" className="btn btn-secondary mt-5 w-full">Review this configuration</Link></article>)}</div><p className="mt-4 text-xs leading-6 text-maven-muted">Website limits apply within one cPanel account. Domain registrations are separate. Published resources are pending supplier activation; confirm runtime versions and migration terms before purchase.</p></div></section>
      <section className="section-space border-y border-maven-line"><div className="container-shell grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeading kicker="Before you order" title="A practical path from selection to setup." /><ol className="steps-list"><li><h3>Check the name and requirements</h3><p>Search for a domain or keep one you own. For applications, list the required language, database and runtime versions.</p></li><li><h3>Review the full billing period</h3><p>Compare the upfront total, renewal price and resource limits. Save selections in your cart; an account is needed for checkout where ordering is enabled.</p></li><li><h3>Confirm what is ready to activate</h3><p>Registration and setup depend on the selected service and its provider. Follow your order status; adding an item to the cart does not activate it.</p></li></ol></div></section>
      <section className="section-space"><div className="container-shell grid gap-8 md:grid-cols-2"><article className="service-summary"><Code2 className="size-5 text-maven-signal" /><h2>Need a developer? Meet Inara Devs.</h2><p>Request developers through Inara Devs for websites, applications and ongoing software maintenance. Development is arranged separately from your MavenHost domain and hosting plan.</p><Link to="/developers">Explore developer options <ArrowRight className="size-4" /></Link><a href={INARA_CREST.developers} target="_blank" rel="noreferrer">Request developers through Inara Devs <span className="sr-only">(opens in a new tab)</span></a></article><article className="service-summary"><h2>Get a clear answer before you move or buy.</h2><p>Send the domain, proposed workload or existing hosting setup to MavenHost support. We can help clarify plan choices, transfer requirements and the next step for a purchased service.</p><Link to="/contact?type=support">Get hosting support <ArrowRight className="size-4" /></Link><Link to="/help-center">Read setup guidance</Link></article></div></section>
    </main><SiteFooter /></div>
}
